In [1]:
# This is the main function to be called for generating a feasible solution connecting the initial and final configurations
# by connecting osculating spheres with same directionality by a cylindrical envelope, and osculating spheres with different
# directionality by conical envelopes.

import os
import sys
from main_functions_heuristic import generate_random_configs_3D, Dubins_3D_numerical_path_on_surfaces
from pathlib import Path
import numpy as np

# Including the following command to ensure that python is able to find the relevant files afer changing directory
sys.path.insert(0, '')
# Obtaining the current directory
cwd = os.getcwd()
# current_directory = Path(__file__).parent
# path_str = str(current_directory)

# Importing code for plotting
rel_path = '\Visualization'
os.chdir(cwd + rel_path)
from visualization_simulation import plot_trajectory

# Returning to initial directory
os.chdir(cwd)

# Here, we provide the description of the initial and final configurations if we
# want to provide the initial and final configurations. For this implementation, we instead generate random initial and final configurations.


# If a random initial and final configuration ought to be generated, we randomly generate the initial and final configurations.
xlim = 40; ylim = 40; zlim = 40; # We provide the region in the 3d space wherein we want to generate the configuration.
# xlim is used to pick a random x coordinate between 0 and xlim; similar interpretation follows for ylim and zlim.
# ini_config = generate_random_configs_3D(xlim, ylim, zlim)
ini_config = np.array([[0, 0, 20],\
                       [1, 0, 0],\
                       [0, 1, 0],\
                       [0, 0, 1]])
# fin_config = generate_random_configs_3D(xlim, ylim, zlim)
# fin_config = np.array([[-8.45673928, -1.0969252 , -9.9048474 ],
#                         [ 0.16004771,  0.70028758,  0.69568817],
#                         [ 0.55203148,  0.52076296, -0.65120441],
#                         [-0.81831899,  0.48826555, -0.30323387]])
fin_config = np.array([[30, 10 , 0],
                        [ 1,  0,  0],
                        [ 0,  1, 0],
                        [0,  0, 1]])

# We now provide the parameters for the vehicle
R = 10 # Radius of the osculating sphere
r = 5 # This is the radius of the tight turn for the vehicle.

# We provide the number of discretizations to be considered for the location and the heading angle
disc_no = 20

# We call the main function that constructs feasible solutions through sphere-cylinder-sphere, sphere-plane-sphere, and sphere-sphere-sphere
# combinations, and returns the path and orientations corresponding to the best path.
min_dist_path_length, min_dist_path_pts, tang_global_path, tang_normal_global_path, surf_normal_global_path, path_type =\
      Dubins_3D_numerical_path_on_surfaces(ini_config, fin_config, r, R, disc_no, visualization = 1, filename = 'temp.html')

print('Tangent vectors for the path are:\n', tang_global_path)

Computing feasible paths through different surfaces.
Considering path construction through cross-tangent plane connecting outer sphere at initial location and inner sphere at final location.
Tangent vectors for the path are:
 [[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 9.99790955e-01  1.77069271e-02 -1.02230991e-02]
 [ 9.99163906e-01  3.54064512e-02 -2.04419241e-02]
 ...
 [ 9.99163906e-01  3.54064512e-02 -2.04419241e-02]
 [ 9.99790955e-01  1.77069271e-02 -1.02230991e-02]
 [ 1.00000000e+00 -2.59528048e-16 -3.52315186e-16]]


In [2]:
path_type

'plane_outer_inner'

In [3]:
%matplotlib qt

# if path_type in ['cyc_inner', 'cyc_outer']:
# We now simulate the motion of a vehicle along the path that we have obtained.
# plot_trajectory(ini_config, fin_config, min_dist_path_pts, tang_global_path, tang_normal_global_path, surf_normal_global_path, path_type, R,\
#                 xgrid_size = [-xlim/2, xlim/2], ygrid_size = [-ylim/2, ylim/2], zgrid_size = [-zlim/2, zlim/2], length_vec_orientation = 10, scale_aircraft = 2.0,\
#                 video_name = False)
plot_trajectory(ini_config, fin_config, min_dist_path_pts, tang_global_path, tang_normal_global_path, surf_normal_global_path, path_type, R,\
                xgrid_size = [-10, 40], ygrid_size = [-5, 20], zgrid_size = [-5, 25], length_vec_orientation = 10, scale_aircraft = 2.0,\
                elev = 27, azim = -58, video_name = '3d_vehicle_descend.mp4') # False)

c:\Users\deepa\anaconda3\lib\site-packages\numpy\lib\function_base.py:518: RuntimeWarning:

Mean of empty slice.

c:\Users\deepa\anaconda3\lib\site-packages\numpy\core\_methods.py:192: RuntimeWarning:

invalid value encountered in scalar divide

